const GRAPHLITE_DEFAULT_DATA_TYPE = 'default';
const GRAPHLITE_PRIMARY_KEY_DATA_TYPE = 'pkey';
const GRAPHLITE_STRING_DATA_TYPE = 'string';
const GRAPHLITE_BOOLEAN_DATA_TYPE = 'bool';
const GRAPHLITE_NUMBER_DATA_TYPE = 'number';
const GRAPHLITE_INTEGER_DATA_TYPE = 'int';
const GRAPHLITE_FLOAT_DATA_TYPE = 'float';
const GRAPHLITE_SUPPORTED_DATA_TYPES = [
  GRAPHLITE_DEFAULT_DATA_TYPE,
  GRAPHLITE_PRIMARY_KEY_DATA_TYPE,
  GRAPHLITE_STRING_DATA_TYPE,
  GRAPHLITE_BOOLEAN_DATA_TYPE,
  GRAPHLITE_NUMBER_DATA_TYPE,
  GRAPHLITE_INTEGER_DATA_TYPE,
  GRAPHLITE_FLOAT_DATA_TYPE,
];
const COUNT_RESPONSE_FIELD_NAME = 'count';
const RESPONSE_OBJECT_NAME = 'response';
const ROW_MATCH_OBJECT_KEY_NAME = '_match';
const DEFAULT_ASSOCIATION_JOIN_TYPE = 'inner';
const GRAPHLITE_CONNECTION_EXECUTER_NAME = 'executeQuery';
const ID_PROPERTY_KEY_NAME = 'id';
const DEFAULT_PAGE_SIZE = 100;
const TOTAL_ROWS_COUNT_PROPERTY_NAME = 'total';

module.exports = {
  GRAPHLITE_SUPPORTED_DATA_TYPES,
  GRAPHLITE_DEFAULT_DATA_TYPE,
  GRAPHLITE_PRIMARY_KEY_DATA_TYPE,
  GRAPHLITE_STRING_DATA_TYPE,
  GRAPHLITE_BOOLEAN_DATA_TYPE,
  GRAPHLITE_NUMBER_DATA_TYPE,
  GRAPHLITE_INTEGER_DATA_TYPE,
  GRAPHLITE_FLOAT_DATA_TYPE,
  COUNT_RESPONSE_FIELD_NAME,
  RESPONSE_OBJECT_NAME,
  DEFAULT_ASSOCIATION_JOIN_TYPE,
  GRAPHLITE_CONNECTION_EXECUTER_NAME,
  ID_PROPERTY_KEY_NAME,
  DEFAULT_PAGE_SIZE,
  TOTAL_ROWS_COUNT_PROPERTY_NAME,
  ROW_MATCH_OBJECT_KEY_NAME,
};
