const GRAPHLITE_DEFAULT_DATA_TYPE = 'default';
const GRAPHLITE_PRIMARY_KEY_DATA_TYPE = 'pkey';
const GRAPHLITE_STRING_DATA_TYPE = 'string';
const GRAPHLITE_BOOLEAN_DATA_TYPE = 'bool';
const GRAPHLITE_NUMBER_DATA_TYPE = 'number';
const GRAPHLITE_INTEGER_DATA_TYPE = 'int';
const GRAPHLITE_FLOAT_DATA_TYPE = 'float';

const GRAPHLITE_SUPPORTED_DATA_TYPES = [
  GRAPHLITE_DEFAULT_DATA_TYPE,
  GRAPHLITE_PRIMARY_KEY_DATA_TYPE,
  GRAPHLITE_STRING_DATA_TYPE,
  GRAPHLITE_BOOLEAN_DATA_TYPE,
  GRAPHLITE_NUMBER_DATA_TYPE,
  GRAPHLITE_INTEGER_DATA_TYPE,
  GRAPHLITE_FLOAT_DATA_TYPE,
];

module.exports = {
  GRAPHLITE_SUPPORTED_DATA_TYPES,
  GRAPHLITE_DEFAULT_DATA_TYPE,
  GRAPHLITE_PRIMARY_KEY_DATA_TYPE,
  GRAPHLITE_STRING_DATA_TYPE,
  GRAPHLITE_BOOLEAN_DATA_TYPE,
  GRAPHLITE_NUMBER_DATA_TYPE,
  GRAPHLITE_INTEGER_DATA_TYPE,
  GRAPHLITE_FLOAT_DATA_TYPE,
};
